baseurl = "https://blog-gainings.com/"
languageCode = "ja"
title = "Gain blog"
theme = "hugo-theme-cactus-plus"
hasCJKLanguage = true 
disqusShortname = "gainings"
# Enable Google Analytics be inserting your tracking code
# Number of posts per page
googleAnalytics = "UA-87988940-1"


[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "gainings"
  facebook = "gai.takano"
  github = "gainings"
  # Disqus shortname
  disqus = "gainings"
  # Google Analytics API key.
	enableGoogleAnalytics = true
  author = "Gainings"
  authorwebsite = "example.com"
  avatar = "/static/images/avatar.jpg"
  contact = "gain.beats@gmail.com"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/static/image/favicon.ico"
	iconFont = "font-awesome"

	enableSummary = true
	
	enableShare = true
	tweet = "Twitter共有"
	enableToc = true


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"

[social]
	facebook-square = "https://www.facebook.com/gai.takano"
	twitter-square = "https://twitter.com/gainings"
	github-square = "https://github.com/gainings"
