baseurl = "https://gainings.github.io/hugo-blog"
languageCode = "ja"
title = "Gain blog"
theme = "hugo-steam-theme"
hasCJKLanguage = true 
disqusShortname = "gainings"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "Gain Blog"
	subtitle = ""
	copyright = ""
  useSummaryIfNoDescription = true
	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Gainings"
	bio = "何者"
	description = "好きなこと書く"
	
	# Link your social networks (optional)
	location = ""
	twitter = "gainings"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "gainings"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Read more"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
